name: minimal_ffi_grpc_example
description: Minimal FFI GRPC Example
version: 0.0.1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  ffi: ^0.1.3
  ffi_helper: ^1.4.0
  protobuf: ^1.0.1
  grpc: ^2.2.0
  shared_ffi_protos:
    path: lib/protos

dev_dependencies:
  build_runner: any

flutter:
  uses-material-design: true
