// Auto-generated by makefile. Do not edit by hand.
library shared_ffi_protos;

import 'package:protobuf/protobuf.dart' as protobuf;
import 'src/greeting.pb.dart';
export 'src/greeting.pb.dart';
export 'src/greeting.pbgrpc.dart';

void createServiceIndexEntries(
    void processOnePackage(
        String package,
        String messages,
        List<MessageType> types,
        List<protobuf.GeneratedMessage Function()> builders,
        String rpcs)) {
  processOnePackage("com.google.greeting", """HelloRequest HelloResponse """, [
    MessageType.HelloRequest,
    MessageType.HelloResponse,
  ], [
    () => new HelloRequest(),
    () => new HelloResponse(),
  ], """//:service Greeter {//:rpc SayHello (HelloRequest) returns (HelloResponse); //:rpc SayHelloAgain (HelloRequest) returns (HelloResponse); }""");
}

enum MessageType {
  HelloRequest,
  HelloResponse,
}
