// Auto-generated by makefile. Do not edit by hand.
pub mod greeting;

use num_derive::FromPrimitive;

#[derive(FromPrimitive)]
pub enum MessageType {
    UnrecognizedMessage = -1,
    HelloRequest = 0,
    HelloResponse = 1,
}
